// ES6 - Export utilities using jsPDF and CSV generation
import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { formatDate, formatCurrency } from './formatters';
import { getCategoryById, EXPENSE_CATEGORIES, INCOME_CATEGORIES } from './constants';

/**
 * Generate and download PDF report (ES6 async/await, arrow functions, template literals)
 */
export const exportToPDF = (transactions, { title = 'Financial Report', dateRange = '' } = {}) => {
  const doc = new jsPDF();

  // Title
  doc.setFontSize(20);
  doc.setTextColor(99, 102, 241);
  doc.text('SpendWise', 14, 20);

  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);
  doc.text(title, 14, 32);

  if (dateRange) {
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text(dateRange, 14, 40);
  }

  // Summary
  const income = transactions
    .filter(t => t.type === 'income')
    .reduce((sum, t) => sum + Number(t.amount), 0);
  const expenses = transactions
    .filter(t => t.type === 'expense')
    .reduce((sum, t) => sum + Number(t.amount), 0);
  const balance = income - expenses;

  const startY = dateRange ? 48 : 42;
  doc.setFontSize(11);
  doc.setTextColor(15, 23, 42);
  doc.text(`Total Income: ${formatCurrency(income)}`, 14, startY);
  doc.text(`Total Expenses: ${formatCurrency(expenses)}`, 14, startY + 8);
  doc.text(`Net Balance: ${formatCurrency(balance)}`, 14, startY + 16);

  // Table
  const tableData = transactions.map(t => {
    const categories = t.type === 'income' ? INCOME_CATEGORIES : EXPENSE_CATEGORIES;
    const category = getCategoryById(categories, t.category);
    return [
      formatDate(t.date),
      t.type === 'income' ? 'Income' : 'Expense',
      category.label,
      t.note || '-',
      formatCurrency(t.amount),
    ];
  });

  doc.autoTable({
    startY: startY + 26,
    head: [['Date', 'Type', 'Category', 'Note', 'Amount']],
    body: tableData,
    headStyles: {
      fillColor: [99, 102, 241],
      textColor: 255,
      fontStyle: 'bold',
    },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    styles: { fontSize: 9, cellPadding: 4 },
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(
      `Generated by SpendWise on ${new Date().toLocaleDateString()}  |  Page ${i} of ${pageCount}`,
      14,
      doc.internal.pageSize.height - 10
    );
  }

  doc.save(`SpendWise_Report_${new Date().toISOString().slice(0, 10)}.pdf`);
};

/**
 * Generate and download CSV report (ES6 arrow functions, map, template literals)
 */
export const exportToCSV = (transactions, filename = 'SpendWise_Report') => {
  const headers = ['Date', 'Type', 'Category', 'Note', 'Amount'];
  
  const rows = transactions.map(t => {
    const categories = t.type === 'income' ? INCOME_CATEGORIES : EXPENSE_CATEGORIES;
    const category = getCategoryById(categories, t.category);
    return [
      formatDate(t.date),
      t.type === 'income' ? 'Income' : 'Expense',
      category.label,
      `"${(t.note || '').replace(/"/g, '""')}"`,
      t.amount,
    ].join(',');
  });

  const csvContent = [headers.join(','), ...rows].join('\n');
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);

  // ES6 - Create download link
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', `${filename}_${new Date().toISOString().slice(0, 10)}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};
